module.exports = {
  'attempt': require('./utility/attempt'),
  'conforms': require('./utility/conforms'),
  'conj': require('./utility/conj'),
  'constant': require('./utility/constant'),
  'disj': require('./utility/disj'),
  'flow': require('./utility/flow'),
  'flowRight': require('./utility/flowRight'),
  'identity': require('./utility/identity'),
  'iteratee': require('./utility/iteratee'),
  'juxt': require('./utility/juxt'),
  'matches': require('./utility/matches'),
  'matchesProperty': require('./utility/matchesProperty'),
  'method': require('./utility/method'),
  'methodOf': require('./utility/methodOf'),
  'mixin': require('./utility/mixin'),
  'noop': require('./utility/noop'),
  'nthArg': require('./utility/nthArg'),
  'property': require('./utility/property'),
  'propertyOf': require('./utility/propertyOf'),
  'range': require('./utility/range'),
  'times': require('./utility/times'),
  'toPath': require('./utility/toPath'),
  'uniqueId': require('./utility/uniqueId')
};
